Задача 1
js-tasks-ru/js-20211109_radik5 pull request #1
Opened 2021-11-10 11:05 UTC by zainullin

Функция по складыванию чисел

2021-11-10 11:05 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @dosandk должен запустить тесты.

2021-11-11 14:21 UTC, dosandk commented on 01-intro/1-sum/index.test.js
> +
этих изменений не должно быть в PR

2021-11-11 14:22 UTC, dosandk requested changes
в PR не должно быть никаких изменений кроме как решения задачи.
Внесение изменений в файлы тестов не допускается, это может сломать систему автоматической проверки

2021-11-11 14:22 UTC, dosandk commented on 01-intro/1-sum/index.js
> +  return m + n;
good 👍

2021-11-11 18:38 UTC, zainullin commented
Исправления добавлены (11 ноября).

2021-11-12 13:38 UTC, dosandk approved these changes
good first step 👍

2021-11-12 13:38 UTC, merged